# Project 3 (Part 2)_A

## Import Libraries

In [13]:
# Standard Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Additional Imports
# os - for saving and loading files
# json - to work with json files
# math - to round up results
# time - to add a short pause to not overwhelm the server
import os, json, math, time
with open(r'/Users/OM22285/.secret/tmdb_api.json') as f:
    login = json.load(f)
## Display the keys of the loaded dict
login.keys()
from tqdm.notebook import tqdm_notebook
import tmdbsimple as tmdb 
tmdb.API_KEY =  login['api-key']
FOLDER = r"C:\Users\om22285\OneDrive - Old Mutual\Documents\Employee Performance\2023\Umluzi Data Science Bootcamp\Coding Dojo Environment\Project-3\Data"
os.makedirs(FOLDER, exist_ok=True)
os.listdir(FOLDER)

# pandas to display maximum columns
pd.set_option('display.max_columns',None)

## Custom Functions

In [2]:
# Custom function to write 
def write_json(new_data, filename): 
    """Appends a list of records (new_data) to a json file (filename). 
    Adapted from: https://www.geeksforgeeks.org/append-to-json-file-using-python/"""  
    
    with open(filename,'r+') as file:
        # First we load existing data into a dict.
        file_data = json.load(file)
        ## Choose extend or append
        if (type(new_data) == list) & (type(file_data) == list):
            file_data.extend(new_data)
        else:
             file_data.append(new_data)
        # Sets file's current position at offset.
        file.seek(0)
        # convert back to json.
        json.dump(file_data, file)

In [3]:
# Get movie rating details
def get_movie_with_rating(movie_id):
    """Adapted from source = https://github.com/celiao/tmdbsimple"""
    # Get the movie object for the current id
    movie = tmdb.Movies(movie_id)

    # save the .info .release dictionaries
    info = movie.info()

    releases = movie.releases()
    # Loop through the countries in releases
    for c in releases['countries']:
        # if the country abbreviation==US
        if c['iso_3166_1'] =='US':
            ## save a "certification" key in info with the certification
            info['certification'] = c['certification']
    return info

In [4]:
# Load in the dataframe from project part 1 as basics:
basics = pd.read_csv('Data/title_basics.csv.gz')

# Display the first 5 rows to confirm title_basics has loaded into the dataframe
basics.head(5)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0034413,short,Youth Gets a Break,Youth Gets a Break,0,2001,NaN,20.0,Short
1,tt0035423,movie,Kate & Leopold,Kate & Leopold,0,2001,NaN,118.0,"Comedy,Fantasy,Romance"
2,tt0111056,tvSeries,Gensomaden Saiyuki,Gensomaden Saiyuki,0,2000,2001.0,23.0,"Action,Adventure,Animation"
3,tt0113026,movie,The Fantasticks,The Fantasticks,0,2000,NaN,86.0,"Musical,Romance"
4,tt0113092,movie,For the Cause,For the Cause,0,2000,NaN,100.0,"Action,Adventure,Drama"

In [5]:
# Define variables

# Years to get (2000 and 2001)
YEARS_TO_GET = [2000, 2001]

# Error list
errors = []

In [ ]:
# Start of OUTER loop
for YEAR in tqdm_notebook(YEARS_TO_GET, desc='YEARS', position=0):
    # Defining the JSON file to store results for the year
    JSON_FILE = f'{FOLDER}tmdb_api_results_{YEAR}.json'
    
    # Check if the file exists
    file_exists = os.path.isfile(JSON_FILE)
    
    # If it does not exist: create it
    if not file_exists:  # Simplified condition
        # Save an empty dict with just "imdb_id" to the new json file.
        with open(JSON_FILE, 'w') as f:
            json.dump([{'imdb_id': 0}], f)

    # Saving the new year as the current df
    df = basics.loc[basics['startYear'] == YEAR].copy()
    # Saving movie ids to list
    movie_ids = df['tconst'].copy()

    # Load existing data from json into a dataframe called "previous_df"
    previous_df = pd.read_json(JSON_FILE)
    # Instead of previous_df=pd.read_json:
    #previous_df = read_and_fix_json(JSON_FILE)

    # Filter out any ids that are already in the JSON_FILE
    movie_ids_to_get = movie_ids[~movie_ids.isin(previous_df['imdb_id'])]

# Get index and movie id from the list
    # INNER Loop
    for movie_id in tqdm_notebook(movie_ids_to_get,
                                  desc=f'Movies from {YEAR}',
                                  position=1,
                                  leave=True):
        try:
            # Retrieve the data for the movie id
            temp = get_movie_with_rating(movie_id)
            # Append/extend results to the existing file using a pre-made function
            write_json(temp, JSON_FILE)
            # Short 20 ms sleep to prevent overwhelming the server
            time.sleep(0.02)

        except Exception as e:
            errors.append([movie_id, e])

    final_year_df = pd.read_json(JSON_FILE)
    final_year_df.to_csv(f"{FOLDER}final_tmdb_data_{YEAR}.csv.gz", compression="gzip", index=False)

print(f"- Total errors: {len(errors)}")